[package]
name = "cli"
version = "0.0.1-Alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.26", default-features = false }

# Compiler
carbon-lang_compiler = { path = "../.." }
